// Package api provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// NewTask defines model for NewTask.
type NewTask struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// Task defines model for Task.
type Task struct {
	// Embedded struct due to allOf(#/components/schemas/NewTask)
	NewTask
	// Embedded fields due to inline allOf schema
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// AddTaskJSONBody defines parameters for AddTask.
type AddTaskJSONBody NewTask

// AddTaskRequestBody defines body for AddTask for application/json ContentType.
type AddTaskJSONRequestBody AddTaskJSONBody
